config/routes.rb
Rails.application.routes.draw do
  resources :patients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'patients#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/patient.rb
class Patient < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:gender, :age, :weight, :bp, :pulse, :temp, :rr, :time, :minutes, :houres, :days, :weeks, :months, :main_view, :lab_view, :document_view, :order_view, :radiology_view)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <title>Dividers</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/patients/_form.html.erb
<%= form_for(patient) do |f| %>
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<center><div class="toprow">

<center>

   <div class="floating-boxxx"><%= link_to  'New Patient Visit', new_patient_path %><br></div>
   <div class="floating-boxxx"><%= link_to  'Load Patient', patients_path %></div>
   <div class="floating-boxxx">Admit<br>patient</div>
   <div class="floating-boxxx">Discharge<br> Session</div>
   <div class="floating-boxxx">Remove <br>Patient</div></center>
   </div><!-- top first buttons-->

</div><!-- topfirstdiv-->
<div class="floating-box1"><!-- main div box1-->
<center><div class="toprow1"><!-- second inner top buttons div-->

  
    <a href="#tabs-1">Nunc tincidunt</a>
    <a href="#tabs-2">Proin dolor</a>
    <a href="#tabs-3">Aenean lacinia</a>
  
</div></center><!-- toprow div end here "buttons"-->

<!--------------------------------------------------------------------- -->
  <div id="tabs-1">
<center><div class="toprowx"><!-- 7butoons start here-->


 <div class="floating-boxfd">
    <div class="field">
    
  <center><font size="3">Gender:</font><%= f.select(:gender, ["male", "female"], {}, :style => "width:100px", :style => "height:27px" ) %></center>
  </div>
  </div>

<div class="floating-boxfd">
  <div class="field">
    
    <center><font size="3">Age:</font><%= f.text_field :age, :size=>"7", :maxlength=>"8" %></center>
  </div>
  </div>

<div class="floating-boxfd">
  <div class="field">
  
    <center><font size="3">Weight:</font><%= f.text_field :weight, :size=>"7", :maxlength=>"8" %></center>
  </div>
  </div>


<div class="floating-boxfd">
  <div class="field">
   
    <center><font size="3">BP:</font><%= f.text_field :bp, :size=>"7", :maxlength=>"8" %></center>
  </div>
</div>


<div class="floating-boxfd">
  <div class="field">
   
    <center><font size="3">Pulse:</font><%= f.text_field :pulse, :size=>"7", :maxlength=>"8" %></center>
  </div>
</div>



<div class="floating-boxfd">
  <div class="field">
    
    <center><font size="3">Temp:</font><%= f.text_field :temp, :size=>"7", :maxlength=>"8" %></center>
  </div>
</div>


<div class="floating-boxfd">
  <div class="field">
    
    <center><font size="3">RR:</font><%= f.text_field :rr, :size=>"7", :maxlength=>"8" %></center>
  </div>
</div>


</div><!-- 7buttons end -->
<!-- --------------------------------------------------------------------------------------------- -->

<div class="meddiv"><!-- this is the meddle div-->

<div class="floating-time"><!-- time box incloude the timestamp-->

<div class="floating-boxtt"><!-- time div box for lables and feilds-->
           <br><br>
  <div class="field">

    <%= f.hidden_field :time , :value => :date %>
  </div>
  <br><br>
  Add Time:
  <br>

        <div class="floating-boxrow">
        <br>
        <%= f.label :minutes %><br>
        <%= f.label :houres %><br>
        <%= f.label :days %><br>
        <%= f.label :weeks %><br>
        <%= f.label :months %><br>
 </div><!-- end the lables-->


        </div><!--end of the first roe text feild-->

      <div class="floating-boxrow">
      <br>
      <%= f.text_field :minutes, :size=>"8", :maxlength=>"8" %>
      <%= f.text_field :houres, :size=>"8", :maxlength=>"8" %>
      <%= f.text_field :days, :size=>"8", :maxlength=>"8" %>
       <%= f.text_field :weeks, :size=>"8", :maxlength=>"8" %>
       <%= f.text_field :months, :size=>"8", :maxlength=>"8" %>

      </div><!-- time stamp ends-->
<div class="floating-boxsub">
<br>
    <center><%= f.submit class: 'buttonsub' %></center>
</div>

</div><!-- end timer div-->
<!-- -------------------------------------- -->


<div class="floating-boxnav">
     
<center><p>
 <br><span onclick="show('Page1');"><font size="4">MAIN</font></span>
 <hr class="style2">
 <span onclick="show('Page2');"><font size="4">LABS</font></span>
  <hr class="style2">
 <span onclick="show('Page3');"><font size="4">DOCUMENTS</font></span>
  <hr class="style2">
 <span onclick="show('Page4');"><font size="4">ORDERS</font></span>
  <hr class="style2">
 <span onclick="show('Page5');"><font size="4">RADIOLOGY</font></span>

</p></center>
  <!-- <div class="btn-group">-->
     
  <!--</div>-->
</div>
<br>
<!--<div class="floating-boxjk"></div>-->
<div class="floating-boxd">

<div id="Page1" class="page" style="display:none">
    <h4>Viewer Main:</h4>
<%= f.text_area :main_view, :id => "m0", :cols => 135, :rows => 10  %>
<h4>Text Entry Main:</h4>
   <textarea type="text" onkeypress ="t(this.value)" rows="7" cols="135"></textarea>

 
</div>
<div id="Page2" class="page" style="display:none">
<h4>Viewer Lab:</h4>
 <%= f.text_area :lab_view, :id => "m1", :cols => 135, :rows => 10 %>
 <h4>Text Entry Lab:</h4>
 <textarea type="text" onkeypress ="t(this.value)" rows="7" cols="135"></textarea>


</div>
<div id="Page3" class="page" style="display:none">
<h4>Viewer doument:</h4>
<%= f.text_area :document_view, :id => "m2", :cols => 135, :rows => 10 %>
<h4>Text Entry Doc:</h4>
   <textarea type="text" onkeypress ="t(this.value)" rows=7 cols="135"></textarea>


</div>

<div id="Page4" class="page" style="display:none">
<h4>Viewer Order:</h4>

 <%= f.text_area :order_view, :id => "m3", :cols => 135, :rows => 10 %>
 <h4>Text Entry Order:</h4>
    <textarea type="text" onkeypress ="t(this.value)" rows="7" cols="135"></textarea>


</div>

<div id="Page5" class="page" style="display:none">
<h4>Viewer Radiology:</h4>
      <%= f.text_area :radiology_view, :id => "m4", :cols => 135, :rows => 10 %>
      <h4>Text Entry Radiology:</h4>
      <textarea type="text" onkeypress ="t(this.value)" rows="7" cols="135"></textarea>
</div>



</div><!-- end of the meddile div -->

</div>


</div><!-- end of the meddiv ----------------------------------------------------------------------------------------------  -->

</center>
</div>
</center>
</div><!-- end of the meddiv ----------------------------------------------------------------------------------------------  -->

</center>

</center>

  </div>
<!-- 99999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999-->
<%= render(:partial => "form7", :local => {:f => f }) %>
<!-- 99999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999-->
<%end%>
</div></center><!---end box1 biggiest box --------------------------------------------------------------------------------------------- -->
<!--- end of the code ----------------------------------------------------------------------------------------------------------------------------- -->



<script type="text/javascript">
  

  function show(elementID) {
    var ele = document.getElementById(elementID);
    if (!ele) {
        alert("no such element");
        return;
    }
    var pages = document.getElementsByClassName('page');
    for(var i = 0; i < pages.length; i++) {
        pages[i].style.display = 'none';
    }
    ele.style.display = 'block';
}
</script> 
<script type="text/javascript">
  $( function() {
    $( "#tabs" ).tabs();
  } );
</script>

app/views/patients/_form1.html.erb
<%= render 'form', patent: @patent %>
<%= form_for @patient do |f| %>
  <% if patent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h @>

i     <ul>
      <% patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<center><div class="toprow">

<div class="floating-box1"><!-- main div box1-->
<center><div class="toprow1"><!-- second inner top buttons div-->
 
</div><!-- toprow div end here "buttons"-->


<center><div class="toprowx"><!-- 7butoons start here-->



</div><!-- 7buttons end -->

<div class="meddiv"><!-- this is the meddle div-->

</div><!-- end of the meddiv-->
</div></center><!---end box1 biggiest box-->
<%end%>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/formmmm.html.erb
 <div class="field">
    <%= f.label :gender %>
    <%= f.text_field :gender %>
  </div>

  <div class="field">
    <%= f.label :age %>
    <%= f.text_field :age %>
  </div>

  <div class="field">
    <%= f.label :weight %>
    <%= f.text_field :weight %>
  </div>

  <div class="field">
    <%= f.label :bp %>
    <%= f.text_field :bp %>
  </div>

  <div class="field">
    <%= f.label :pulse %>
    <%= f.text_field :pulse %>
  </div>

  <div class="field">
    <%= f.label :temp %>
    <%= f.text_field :temp %>
  </div>

  <div class="field">
    <%= f.label :rr %>
    <%= f.text_field :rr %>
  </div>

  <div class="field">
    <%= f.label :time %>
    <%= f.datetime_select :time %>
  </div>

  <div class="field">
    <%= f.label :minutes %>
    <%= f.text_field :minutes %>
  </div>

  <div class="field">
    <%= f.label :houres %>
    <%= f.text_field :houres %>
  </div>

  <div class="field">
    <%= f.label :days %>
    <%= f.text_field :days %>
  </div>

  <div class="field">
    <%= f.label :weeks %>
    <%= f.text_field :weeks %>
  </div>

  <div class="field">
    <%= f.label :months %>
    <%= f.text_field :months %>
  </div>

  <div class="field">
    <%= f.label :main_view %>
    <%= f.text_area :main_view %>
  </div>

  <div class="field">
    <%= f.label :lab_view %>
    <%= f.text_area :lab_view %>
  </div>

  <div class="field">
    <%= f.label :document_view %>
    <%= f.text_area :document_view %>
  </div>

  <div class="field">
    <%= f.label :order_view %>
    <%= f.text_area :order_view %>
  </div>

  <div class="field">
    <%= f.label :radiology_view %>
    <%= f.text_area :radiology_view %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>




<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Patients</h1>

<table>
  <thead>
    <tr>
      <th>Gender</th>
      <th>Age</th>
      <th>Weight</th>
      <th>Bp</th>
      <th>Pulse</th>
      <th>Temp</th>
      <th>Rr</th>
      <th>Time</th>
      <th>Minutes</th>
      <th>Houres</th>
      <th>Days</th>
      <th>Weeks</th>
      <th>Months</th>
      <th>Main view</th>
      <th>Lab view</th>
      <th>Document view</th>
      <th>Order view</th>
      <th>Radiology view</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.gender %></td>
        <td><%= patient.age %></td>
        <td><%= patient.weight %></td>
        <td><%= patient.bp %></td>
        <td><%= patient.pulse %></td>
        <td><%= patient.temp %></td>
        <td><%= patient.rr %></td>
        <td><%= patient.time %></td>
        <td><%= patient.minutes %></td>
        <td><%= patient.houres %></td>
        <td><%= patient.days %></td>
        <td><%= patient.weeks %></td>
        <td><%= patient.months %></td>
        <td><%= patient.main_view %></td>
        <td><%= patient.lab_view %></td>
        <td><%= patient.document_view %></td>
        <td><%= patient.order_view %></td>
        <td><%= patient.radiology_view %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<%= render 'form', patient: @patient %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Gender:</strong>
  <%= @patient.gender %>
</p>

<p>
  <strong>Age:</strong>
  <%= @patient.age %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @patient.weight %>
</p>

<p>
  <strong>Bp:</strong>
  <%= @patient.bp %>
</p>

<p>
  <strong>Pulse:</strong>
  <%= @patient.pulse %>
</p>

<p>
  <strong>Temp:</strong>
  <%= @patient.temp %>
</p>

<p>
  <strong>Rr:</strong>
  <%= @patient.rr %>
</p>

<p>
  <strong>Time:</strong>
  <%= @patient.time %>
</p>

<p>
  <strong>Minutes:</strong>
  <%= @patient.minutes %>
</p>

<p>
  <strong>Houres:</strong>
  <%= @patient.houres %>
</p>

<p>
  <strong>Days:</strong>
  <%= @patient.days %>
</p>

<p>
  <strong>Weeks:</strong>
  <%= @patient.weeks %>
</p>

<p>
  <strong>Months:</strong>
  <%= @patient.months %>
</p>

<p>
  <strong>Main view:</strong>
  <%= @patient.main_view %>
</p>

<p>
  <strong>Lab view:</strong>
  <%= @patient.lab_view %>
</p>

<p>
  <strong>Document view:</strong>
  <%= @patient.document_view %>
</p>

<p>
  <strong>Order view:</strong>
  <%= @patient.order_view %>
</p>

<p>
  <strong>Radiology view:</strong>
  <%= @patient.radiology_view %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>